# Generated by Django 5.0.1 on 2024-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tid",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
