# Generated by Django 5.0.1 on 2024-03-18 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0004_gift"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firstapp.gift"
                    ),
                ),
            ],
        ),
    ]
