# Generated by Django 5.0.1 on 2024-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0007_users_reward_claimed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("task_id", models.CharField(max_length=100)),
            ],
        ),
    ]
