# Generated by Django 5.0.1 on 2024-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0008_completedtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="nickname",
            field=models.IntegerField(default=1),
        ),
    ]
