# Generated by Django 5.0.1 on 2024-03-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0010_alter_users_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(unique=True)),
                ("image_url", models.URLField()),
            ],
        ),
    ]
