# Generated by Django 5.0.1 on 2024-03-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0011_userlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
