# Generated by Django 5.0.1 on 2024-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0013_usergift_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
