# Generated by Django 5.0.1 on 2024-04-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0015_gift_description_usergift_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergift",
            name="created_at",
        ),
        migrations.AddField(
            model_name="usergift",
            name="used_gift",
            field=models.BooleanField(default=False),
        ),
    ]
